[project]
name = "qc-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "qiskit>=2.2.3",
    "qiskit-aer>=0.17.2",
]
